.PHONY: server client

server:
	g++ Server.cpp -w -lSDL2 -lSDL2_image -lSDL2_ttf -lSDL2_mixer -o Server
	./Server

client:
	g++ Client.cpp -w -lSDL2 -lSDL2_image -lSDL2_ttf -lSDL2_mixer -o Client
	./Client
